// Generated by https://quicktype.io

export interface Producto {
    _id:            string;
    nombre:         string;
    descripcion:    string;
    categoria:      string[];
    imageUrl:       ImageURL[];
    precio_venta:   number;
    precio_regular: number;
    slug?:           string; /*opcional */
    created_at:Date;
    update_at?:Date;
}

export enum ImageURL {
    AssetsImgProductos1Jpg = "../../assets/img-productos/1.jpg",
}
